freq_multiplier:
  W-MON: 52
  WOM-1MON: 12
  D: 365

default_params:
  buy_amount: 10.0
  freq: "W-MON"
  fee: 0.01
  minimum_profit: 1.1
  cooldown_wait: 7
  manual_sell_fraction: null

  sell_fraction:
    low: 0.25
    medium: 0.5
    high: 1.0

  cooldown_days:
    low: 30
    medium: 90
    high: 999

  enable_sell: true
  enable_model: false
  enable_ma200: true
  enable_ma20: true
  enable_zscore: true
  enable_portfolio: true
  enable_rsi: true
  threshold_invest_years: 4.0
  threshold_model_sell: 0.5
  threshold_ma200_sell: 2.0
  threshold_zscore_sell: 2.0
  threshold_rsi_sell: 80.0

banking_rate: 0.02