freq_multiplier:
  W-MON: 52
  WOM-1MON: 12
  D: 365

default_params:
  buy_amount: 10.0
  freq: "W-MON"
  fee: 0.01

  minimum_profit: 1.5
  minimum_loss: 0.5

  cooldown_wait: 7
  cooldown_days: 30

  manual_sell_fraction: 0.5

  enable_sell: true
  enable_extra_buy: true
